import re
from playwright.sync_api import Page, expect

from conftest import shared_page
from pages.home_page import HomePage
from pages.login_page import LoginPage
from pages.recruitment_page import RecruitmentPage
from pages.logout_page import LogoutPage

def test_HomePage(shared_page):
    print("\nStarting test_HomePage transaction")
    print("Will go to home page")
    shared_page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    print("Loaded home page")
    home_page = HomePage(shared_page)
    home_page.verify_branding_image_visible()
    print("Verified branding image is visible on the home page")
    print("Ended test_HomePage transaction")

def test_LoginPage(shared_page):
    print("\nStarting test_LoginPage transaction")
    login_page = LoginPage(shared_page)
    print("Enter username and password and click Login button")
    login_page.login("Admin", "admin123")
    print("Clicked Login button")
    expect(shared_page.get_by_role("heading", name="Dashboard")).to_be_visible()
    shared_page.wait_for_selector("//h6[contains(.,'Dashboard')]")
    print("Verified Dashboard heading is visible on the dashboard page")
    print("Ended test_LoginPage transaction")

def test_RecruitmentPageSearchByTitle(shared_page):
    print("\nStarting test_RecruitmentPageSearchByTitle transaction")
    recruitment_page = RecruitmentPage(shared_page)
    print("Will click on Recruitment menu")
    recruitment_page.click_recruitment_menu()
    print("Clicked on Recruitment menu")
    print("Will click on Job Title dropdown")
    recruitment_page.click_job_title_dropdown()
    print("Clicked on Job Title dropdown")
    print("Will select Software Engineer option from the dropdown")
    recruitment_page.click_software_engineer_option()
    print("Selected Software Engineer option from the dropdown")
    print("Will click on Search button")
    recruitment_page.click_search_button()
    print("Clicked on Search button")
    expect(shared_page.get_by_role("cell", name="Software Engineer").first).to_be_visible()
    print("Verified Software Engineer job title is visible in the search results")
    expect(shared_page.locator("span", has_text=re.compile(r"Records? Found"))).to_be_visible()
    print("Verified Records Found is visible in the search results")
    print("Ended test_RecruitmentPageSearchByTitle transaction")

def test_RecruitmentPageSearchByVacancy(shared_page):
    print("\nStarting test_RecruitmentPageSearchByVacancy transaction")
    recruitment_page = RecruitmentPage(shared_page)
    print("Will click on Recruitment menu")
    recruitment_page.click_recruitment_menu()
    print("Clicked on Recruitment menu")
    print("Will click on Vacancy dropdown")
    recruitment_page.click_vacancy_dropdown()
    print("Clicked on Vacancy dropdown")
    print("Will select Software Engineer option from the dropdown")
    recruitment_page.click_software_engineer_vacancy_option()
    print("Selected Software Engineer option from the dropdown")
    print("Will click on Search button")
    recruitment_page.click_search_button()
    print("Clicked on Search button")
    expect(shared_page.get_by_role("cell", name="Software Engineer").first).to_be_visible()
    print("Verified Software Engineer job title is visible in the search results")
    expect(shared_page.locator("span", has_text=re.compile(r"Records? Found"))).to_be_visible()
    print("Verified Records Found is visible in the search results")
    print("Ended test_RecruitmentPageSearchByVacancy transaction")

def test_RecruitmentPageSearchByHiringManager(shared_page):
    print("\nStarting test_RecruitmentPageSearchByHiringManager transaction")
    recruitment_page = RecruitmentPage(shared_page)
    print("Will click on Recruitment menu")
    recruitment_page.click_recruitment_menu()
    print("Clicked on Recruitment menu")
    print("Will click on Hiring Manager dropdown")
    recruitment_page.click_hiring_manager_dropdown()
    print("Clicked on Hiring Manager dropdown")
    print("Will select first option from the dropdown")
    recruitment_page.click_hiring_manager_dropdown_first_option()
    print("Selected first option from the dropdown")
    print("Will click on Search button")
    recruitment_page.click_search_button()
    print("Clicked on Search button")
    expect(shared_page.locator("span", has_text=re.compile(r"Records? Found"))).to_be_visible()
    print("Verified Records Found is visible in the search results")
    print("Ended test_RecruitmentPageSearchByHiringManager transaction")

def test_RecruitmentPageSearchByStatus(shared_page):
    print("\nStarting test_RecruitmentPageSearchByStatus transaction")
    recruitment_page = RecruitmentPage(shared_page)
    print("Will click on Recruitment menu")
    recruitment_page.click_recruitment_menu()
    print("Clicked on Recruitment menu")
    print("Will click on Status dropdown")
    recruitment_page.click_status_dropdown()
    print("Clicked on Status dropdown")
    print("Will select Application Initiated option from the dropdown")
    recruitment_page.click_status_dropdown_application_initiated_option()
    print("Selected Application Initiated option from the dropdown")
    print("Will click on Search button")
    recruitment_page.click_search_button()
    print("Clicked on Search button")
    expect(shared_page.locator("span", has_text=re.compile(r"Records? Found"))).to_be_visible()
    print("Verified Records Found is visible in the search results")
    print("Ended test_RecruitmentPageSearchByStatus transaction")

def test_RecruitmentPageSearchByKeywords(shared_page):
    print("\nStarting test_RecruitmentPageSearchByKeywords transaction")
    recruitment_page = RecruitmentPage(shared_page)
    print("Will click on Recruitment menu")
    recruitment_page.click_recruitment_menu()
    print("Clicked on Recruitment menu")
    print("Will click on Keywords textbox")
    recruitment_page.click_keywords_textbox()
    print("Clicked on Keywords textbox")
    print("Will enter keywords in the textbox")
    recruitment_page.enter_keywords("Test")
    print("Entered keywords in the textbox")
    print("Will click on Search button")
    recruitment_page.click_search_button()
    print("Clicked on Search button")
    expect(shared_page.locator("span", has_text=re.compile(r"Records? Found"))).to_be_visible()
    print("Verified Records Found is visible in the search results")
    print("Ended test_RecruitmentPageSearchByKeywords transaction")

def test_RecruitmentPageVacanciesSearchByJobTitle(shared_page):
    print("\nStarting test_RecruitmentPageVacanciesSearchByJobTitle transaction")
    recruitment_page = RecruitmentPage(shared_page)
    print("Will click on Vacancies submenu")
    recruitment_page.click_vacancies_submenu()
    print("Clicked on Vacancies submenu")
    print("Will click on Job Title dropdown")
    recruitment_page.click_job_title_dropdown()
    print("Clicked on Job Title dropdown")
    print("Will select Account Assistant option from the dropdown")
    recruitment_page.click_job_title_dropdown_account_assistant_option()
    print("Selected Account Assistant option from the dropdown")
    print("Will click on Search button")
    recruitment_page.click_search_button()
    print("Clicked on Search button")
    expect(shared_page.locator("span", has_text=re.compile(r"Records? Found"))).to_be_visible()
    print("Verified Records Found is visible in the search results")
    print("Ended test_RecruitmentPageVacanciesSearchByJobTitle transaction")

def test_Logout(shared_page):
    print("\nStarting test_Logout transaction")
    logout_page = LogoutPage(shared_page)
    print("Will click on logout option on the menu")
    logout_page.click_logout()
    print("Clicked on logout option on the menu")
    expect(shared_page.get_by_role("button", name="Login")).to_be_visible()
    print("Verified Login button is visible on the login page after logout")
    print("Ended test_Logout transaction")
